### ISSUE TITLE
ModuleNotFoundError: No module named 'tools_folder'

### ISSUE THREAD

**Issue by qxiaomay** [Yiouki/generate_usable_base#1]
Hi, I want to run this code to process jpeg images, and I found the tools folder is empty.
Could you please fix the jpeg tools folder. Thank you very much! 
![微信图片_20200103175208](https://user-images.githubusercontent.com/24953690/71717076-d476b700-2e51-11ea-87d5-d9350c345385.png)

**Comment by Yiouki** [comment]
> Hi, I want to run this code to process jpeg images, and I found the tools folder is empty.
> Could you please fix the jpeg tools folder. Thank you very much!
> ![微信图片_20200103175208](https://user-images.githubusercontent.com/24953690/71717076-d476b700-2e51-11ea-87d5-d9350c345385.png)

Hi,
You're right, I forgot to commit the update of the folder, now it's ok.
Let me know if you have more problems.
